<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYh5stl3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYh5stl3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYh5stl3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYh5stl3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYh5stl3\appProdProjectContainer([
    'container.build_hash' => 'Yh5stl3',
    'container.build_id' => '3e9d19a1',
    'container.build_time' => 1678225200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYh5stl3');
